USE [master]
GO
CREATE LOGIN [spsAdmin] WITH PASSWORD=N'password', DEFAULT_DATABASE=[CRUD], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [CRUD]
GO
CREATE USER [spsAdmin] FOR LOGIN [spsAdmin]
GO
USE [CRUD]
GO
ALTER ROLE [db_datareader] ADD MEMBER [spsAdmin]
GO