USE [master]
GO
CREATE LOGIN spsGuest WITH PASSWORD=N'password', DEFAULT_DATABASE=CRUD, CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE CRUD
GO
CREATE USER spsGuest FOR LOGIN spsGuest
GO
USE CRUD
GO
ALTER ROLE [db_datareader] ADD MEMBER spsGuest
GO

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON
AcadProgramme
TO spsGuest;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON
DrugRehabProgramme
TO spsGuest;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON
InmateProgress
TO spsGuest;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON
Inmates
TO spsGuest;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON
Users
TO spsGuest;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON
VocationalProgramme
TO spsGuest;